name: nats
version: 2.1.2
summary: A simple, secure and high performance open source messaging system
description: |
  NATS.io is a simple, secure and high performance open source messaging system for cloud
  native applications, IoT messaging, and microservices architectures.
confinement: strict
grade: stable
architectures: [amd64, arm64]

apps:
  server:
    daemon: simple
    command: bin/start-nats.sh
    plugs: [network-bind]

parts:
  nats:
    plugin: go
    go-importpath: github.com/nats-io/nats-server/v2
    source: https://github.com/nats-io/nats-server
    source-tag: v2.1.2
    source-type: git
    build-snaps:
    - go/1.13/stable
    override-build: |
      unset GOPATH
      export GO111MODULE=on
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/bin
      for arch in amd64 arm64 ; do
        GOARCH="$arch" go build -mod vendor -o "nats-server.$arch" .
        cp "nats-server.$arch" "$SNAPCRAFT_PART_INSTALL"/bin
      done
    stage:
    - bin/nats-server.amd64
    - bin/nats-server.arm64

  scripts:
    plugin: dump
    source: scripts
    organize:
      start-nats.sh: bin/start-nats.sh
    stage:
    - bin/start-nats.sh
